### ISSUE TITLE
Asura Scans "No pages found"

### ISSUE THREAD

**Issue by mdpolson** [tachiyomiorg/tachiyomi-extensions#15468]
### Source information and language

Asura Scans v1.4.42

### Steps to reproduce

1. Install Asura Scans extension if not already installed
2. Select any series from Asura Scans
3. Attempt to download any chapter
4. Download will fail with error message "No pages found"

### Expected behavior

The download should succeed.

### Actual behavior

The download fails with error message "No pages found"

### Tachiyomi version

0.14.5

### Android version

Android 13 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Mondotosz** [comment]
I'm using TachiyomiJ2K v1.6.2 and also getting this issue with asura scans and reaper scans.
Tried it on TachiyomiSY v1.9.0 and it doesn't occur there.

**Comment by asdkant** [comment]
Can confirm this happens with TachiJ2K v1.6.2 + asura v1.4.42 with both downloading and reading non-downloaded

**Comment by leehwongxing** [comment]
Reading directly on Asura IS slow atm, but Reaper is still fast, but from the extension, Asura return no page and Reaper return extra yet non existing page.

**Comment by rytt0001** [comment]
Had this problem on TachiyomiSy 1.9.0 with asurascan 1.4.42
Fixed it by resetting the User agent string in 
parameter ->advanced
If you want to know your user agent of your browser :
https://www.whatismybrowser.com/detect/what-is-my-user-agent/

**Comment by leehwongxing** [comment]
> Had this problem on TachiyomiSy 1.9.0 with asurascan 1.4.42 Fixed it by resetting the User agent string in parameter ->advanced If you want to know your user agent of your browser : https://www.whatismybrowser.com/detect/what-is-my-user-agent/

unfortunately, this doesnt work on latest j2k build as i set the user-agent globally, and 1.4.* remove the ability to change user-agent on each extension

**Comment by conztanz045** [comment]
Need this setting in extension
![Screenshot_2023-02-26-01-25-07-22](https://user-images.githubusercontent.com/79831076/221370946-8e6906f4-3d63-4ae1-abf7-01cc0f46358c.jpg)

**Comment by Mozef** [comment]
For 0.14.5
Settings->advanced-> reset the default user under the network section
It fixes for me. ( For asura, reaper still have the weird loading)

**Comment by ArjixWasTaken** [comment]
I can confirm that changing the user agent works.

Mine is:
```
Mozilla/5.0 (X11; Linux i686) AppleWebKit/5342 (KHTML, like Gecko) Chrome/36.0.858.0 Mobile Safari/5342
```

**Comment by PranjalBorthakur** [comment]
> I can confirm that changing the user agent works.
> 
> Mine is:
> 
> ```
> Mozilla/5.0 (X11; Linux i686) AppleWebKit/5342 (KHTML, like Gecko) Chrome/36.0.858.0 Mobile Safari/5342
> ```

I tested it out and it works.
