### ISSUE TITLE
[LANraragi] Parameter specified as non-null is null: method kotlin.text.StrigsKt_Strings__JVMKt.replace,parameter $this$replace

### ISSUE THREAD

**Issue by tillettkember** [tachiyomiorg/tachiyomi-extensions#9995]
### Source information

LANraragi - 1.2.7

### Steps to reproduce

1. Configure your extension according to the server you're using
2. Open the library of LANraragi through the "sources" section of the Tachiyomi app

### Expected behavior

The entire library of the chose LANraragi server would show up as if was another server, just like the other extensions do.

### Actual behavior

The error mentioned in title (Parameter specified as non-null is null: method kotlin.text.StrigsKt_Strings__JVMKt.replace,parameter $this$replace) shows up.

### Tachiyomi version

0.12.3

### Android version

10

### Other details

The server is updated to version 0.8.3, but this issue only started ocurring after the extension was updated to 1.2.6.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
This should fix the issue but I can't test it.
```diff
--- i/src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/LANraragi.kt
+++ w/src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/LANraragi.kt
@@ -233,7 +233,7 @@ open class LANraragi : ConfigurableSource, HttpSource() {
         title = archive.title
         description = archive.title
         thumbnail_url = getThumbnailUri(archive.arcid)
-        genre = archive.tags.replace(",", ", ")
+        genre = archive.tags?.replace(",", ", ")
         artist = getArtist(archive.tags)
         author = artist
         status = SManga.COMPLETED
--- i/src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/model/Archive.kt
+++ w/src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/model/Archive.kt
@@ -3,6 +3,6 @@ package eu.kanade.tachiyomi.extension.all.lanraragi.model
 data class Archive(
     val arcid: String,
     val isnew: String,
-    val tags: String,
+    val tags: String?,
     val title: String
 )
```

**Comment by RePod** [comment]
It could be handled by the extension, but the server is most likely returning `null` for archives added within a specific timeframe and since fixed for new archives. While the replace is presumptuous the problematic archives *should* be fixed by running Batch Operations - Use Plugin: Tag Copier from the server.

**Comment by tillettkember** [comment]
> It could be handled by the extension, but the server is most likely returning `null` for archives added within a specific timeframe (pre-0.7.8) and since fixed for new archives. While the replace is presumptuous the problematic archives _should_ be fixed by running Batch Operations - Use Plugin: Tag Copier - Override Plugin Global Arguments: _something_ from the server.

That seems to be a possible solution to the issue, although sadly that is not a feasible solution to an old issue with LANraragi itself, the error 1006 makes this kinda impossible sadly.
I've tested adding one new file onto the server, and indeed, the new gallery has a tag called "date_added: randomstringofnumbers", while the older ones are missing. Sadly, the extension will still throw the same error message as expected, so I cannot confirm this tag as the main culprit of the issue.
I'll remove my entire library and try to readd the files as if they were brand new and update the topic with the results when done.

**Comment by RePod** [comment]
The problem can be replicated from redis-cli to force a `null`:
```
KEYS *
HGETALL hash
HDEL hash tags
```
I don't know enough about redis for a way to iterate over all missing `tags` except for `HSETNX hash tags ""` individually. It seems to supports external scripting, but that's outside the scope of the extension.
For what it's worth, the server's web reader has the [same problem.](https://user-images.githubusercontent.com/7897871/144714047-567b0a77-5de9-46d8-9833-3cb7bf8bf3c0.png)
